export enum BlogsActionType {
  FETCH_BLOGS_LOADING = "FETCH_BLOGS_LOADING",
  FETCH_BLOGS_SUCCESS = "FETCH_BLOGS_SUCCESS",
  FETCH_BLOGS_FAILURE = "FETCH_BLOGS_FAILURE",
  CREATE_BLOG = "CREATE_BLOG"
}
